version: '3.8'

services:
  # Message Broker: Handles asynchronous messaging between microservices
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Communication port for microservices
      - "15672:15672" # Web Dashboard port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge